# Generated by Django 5.0.1 on 2024-01-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_clients',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='contacts.contact'),
        ),
    ]
