# Generated by Django 5.0.1 on 2024-01-16 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_task_assigned_clients'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='color',
            field=models.CharField(default='default_color', max_length=15),
        ),
    ]
