# Generated by Django 5.0.1 on 2024-01-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_topic_color_alter_task_assigned_clients_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='subtasks',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
